thymeleaf:
  cache: false
  check-template: true
  check-template-location: true
  content-type: text/html
  enabled: true
  encoding: UTF-8
  excluded-view-names:
  mode: HTML5
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 8080

spring:
#  sql:
#    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
